name: test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install lib criterion
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libcriterion-dev
    - name: Build and test C code
      run: |
        make
        make check
